from grafo import Grafo
g = Grafo(dirigido=False)

g.insertar_vertice('Cocina')
g.insertar_vertice('Comedor')
g.insertar_vertice('Cochera')
g.insertar_vertice('Quincho')
g.insertar_vertice('Baño 1')
g.insertar_vertice('Baño 2')
g.insertar_vertice('Habitacion 1')
g.insertar_vertice('Habitacion 2')
g.insertar_vertice('Sala de estar')
g.insertar_vertice('Terraza')
g.insertar_vertice('Patio')


g.insertar_arista('Cocina', 'Comedor', 2)
g.insertar_arista('Cocina', 'Baño 1', 5)
g.insertar_arista('Cocina', 'Patio', 1)
g.insertar_arista('Cocina', 'Quincho', 10)
g.insertar_arista('Cocina', 'Cochera', 7)
g.insertar_arista('Comedor', 'Quincho', 12)
g.insertar_arista('Comedor', 'Baño 1', 2)
g.insertar_arista('Comedor', 'Habitacion 1', 4)
g.insertar_arista('Comedor', 'Habitacion 2', 5)
g.insertar_arista('Comedor', 'Terraza', 10)
g.insertar_arista('Cochera', 'Patio', 15)
g.insertar_arista('Cochera', 'Comedor', 6)
g.insertar_arista('Cochera', 'baño 1', 2)
g.insertar_arista('Quincho', 'Habitacion 2', 8)
g.insertar_arista('Quincho', 'Baño 1', 6)
g.insertar_arista('Quincho', 'Patio', 10)
g.insertar_arista('Baño 1', 'Terraza', 10)
g.insertar_arista('Baño 1', 'Habitacion 1', 10)
g.insertar_arista('Baño 1', 'Patio', 10)
g.insertar_arista('Baño 2', 'Terraza', 2)
g.insertar_arista('Baño 2', 'Comedor', 8)
g.insertar_arista('Baño 2', 'Sala de estar', 10)
g.insertar_arista('Habitacion 1', 'Terraza', 10)
g.insertar_arista('Habitacion 1', 'Comedor', 3)
g.insertar_arista('Habitacion 1', 'Baño 1', 4)
g.insertar_arista('Habitacion 2', 'Patio', 10)
g.insertar_arista('Habitacion 2', 'Cochera', 3)
g.insertar_arista('Habitacion 2', 'Cocina', 6)
g.insertar_arista('Sala de estar', 'Terraza', 5)
g.insertar_arista('Sala de estar', 'Cochera', 10)
g.insertar_arista('Sala de estar', 'Baño 2', 3)
g.insertar_arista('Terraza', 'Quincho', 4)
g.insertar_arista('Terraza', 'Comedor', 8)
g.insertar_arista('Terraza', 'Baño 2', 7)
g.insertar_arista('Patio', 'Quincho', 2)
g.insertar_arista('Patio', 'Sala de estar', 5)
g.insertar_arista('Patio', 'Cochera', 6)

print('arbol de expasion minima')
arbol_min=g.kruskal()
print(arbol_min)
peso_total = 0
arbol_min = arbol_min[0].split('-')
for nodo in arbol_min:
    nodo = nodo.split(';')
    peso_total += int(nodo[2])
    print(f'{nodo[0]}-{nodo[1]}-{nodo[2]}')

print(f"la cantidad de metros total es {peso_total}")
print()
print('camino mas corto')
print()
if(g.existe_paso('Habitacion 1','Sala de estar')):
    resultados1 = g.dijkstra('Habitacion 1')
    camino = g.camino(resultados1, 'Habitacion 1', 'Sala de estar')
    print(camino)
else:
    print('no existe paso, no se puede calcular el camino mas corto')
